### ISSUE TITLE
Month vise Report

### ISSUE THREAD

**Issue by sidheeq** [prashants/webzash-v1-defunct#6] opened 2012-09-26 11:40 UTC
Hai, brother, 
You are appreciated  for this good work , god bless you  
I check this program , and i cant find these simple  report 

1- Not available month vise report of any transaction report , 
2 - Not available a specif period report 
3 Not available daily transaction report 
please add this also
sidheeq T

**Comment by prashants** [comment] 2012-09-30 12:43
If you can help develop that part I will help you merge your code.

**Comment by kjcpa** [comment] 2013-02-20 22:24
I downloaded the program last week, and it works. It is a good program.

For the report issue, my solution is as follows:

1)'settings' table: add "period_start" and "period_end". 

2)"entry.php" controller: add "->where('entries.date >=', $period_start)->where('entries.date <=', $period_end) "

3)"ledgerst.php": same as above.

4)for Trial Balance: add "date" column to "entry_items" table. "entry.php" controller: add 'date' => $data_date for ledger accounts.

5)For "ledger_model.php", add "

->where('entry_items.date <=', $period_end)" for the Balance Sheet ledger accounts 

and  

"->where('entry_items.date >=', $period_start)->where('entry_items.date <=', $period_end) " for Income Statement ledger accounts.

Add a line such as "Retained Earnings Prior to Report Period" to make the "TOTAL" Dr=Cr.

You may calculate Net Income or Loss for the Report Period.

6)Balance Sheet and Profit & Loss: may use the figures on the Trial Balance.

**Comment by kjcpa** [comment] 2013-02-20 22:29
I don't have to use more than one DB because I use fy_start and fy_end to control the active accounting year for entering data, and period_start and period-end to control the report period for reporting.

**Comment by kjcpa** [comment] 2013-02-20 22:40
7)Ledger Account Numbers:
1001-1999 for Assets
2001-2499 for Liabilities
2501-2999 for Equity
3001-3999 for Incomes
4001-4999 for Cost of Goods Sold
5001-5999 for Expenses
6001-6999 for Other Income
7001-7999 for Other Expense

**Comment by ghost** [comment] 2013-02-21 05:17
One small suggestion : Rather than adding period to database, you can store it as a session variable. Since different users might be accessing it for different periods so we can save it in per user session variable.

Also if you can code that part and send me it in patch format or email me the php files. Also post your proposed solution before you actually code.

**Comment by kjcpa** [comment] 2013-02-22 07:33
Good idea. 
Thanks, octabrain.  

Let the users input the start date and end date every time when a report is going to be generated, but not to select the dates from settings and update settings. 

Not to change the settings table.

**Comment by kjcpa** [comment] 2013-02-24 04:02
I used the same trialbalance.php for Blance Sheet and Profit and Loss Statement.

The demo is at 

http://www.jeong.us/webzash

**Comment by zxcasv** [comment] 2013-03-07 13:42
@kjcpa, do you mind to share your webzash source code?
because I downloaded the prashans' source code (the zip-ball), and when I tried to add a ledger (in chart of account), the calculation is incorrect.
I've tried your demo, and it seems yours is better..
I don't quite understand the CI, but I just need to run this code in my localhost for my university task..

I hope you don't mind to share and help me..

thank you in advance..

**Comment by prashants** [comment] 2013-03-07 16:36
Hi,

Sorry I am not finding time to do development and looking for maintainers who can carry forward with the development. If anyone is interested let me know, I dont mind passing the responsibility to him. I have a list of things that needs to be done.

> because I downloaded the prashans' source code (the zip-ball), and when I tried to add a ledger (in chart of 
> account), the calculation is incorrect.

Can you show a screenshot ?

Regards.

**Comment by prashants** [comment] 2013-03-07 16:37
@kjcpa - if you can send the patches for the enhancements that you have made, everyone else can benefit from it.

**Comment by prashants** [comment] 2013-03-07 16:43
I saw the "change" option that you have made. Looks good but needs some polish in the UI side. Is the change option for the reports only ? Then you can add a link on the top of all the reports page. Maybe if I get time this sunday I will merge this most sorted after request from users.

**Comment by kjcpa** [comment] 2013-03-07 21:27
I am not an IT man. What I made is very messy. I will send everything to prashants for his information only. 

The key points are: for balance sheet accounts, count everything from the very beginning to the end of the report period; for profit and loss accounts, from the beginning of report period to the end of the report period. The different is the Retained Earnings or something else.

Because Dr = Cr, when a new ledger account is created, it is better to have the user to input the opening balance to both Dr and Cr sides. Or, don't allow the users to input the opening balance at all, and let them do it under Entries. The O/P Balance under Account does not have to be used.

One database only. I can use the Change option to change accounting year, so it is not necessary to use one database for each year.

zxcasv: please wait because prashants will issue the update.

It does not work under CodeIgniter 2.13.

**Comment by kjcpa** [comment] 2013-03-07 22:21
Prashant,

Here is the changes I made. Please note that my changes are very messy.
 
Regards,

**Comment by zxcasv** [comment] 2013-03-08 07:10
@prashants 
Hi Prashants, I thought this project has been abandoned.
I cannot give you screen shot at the moment, but I'll tell you what happened:
Firstly, after I put your code in my localhost, I create an account, and add a ledger into the chart of accounts, with these fields:
- Ledger Name : Building
- Parent Group : Current Assets
- Opening Balance: Dr 1000000
- I didn't tick on the two check-boxes below, and just click Create.
  Then it navigate back to the Chart of Account page.

At this page (CoA), it showed me that the Difference in Opening Balance is Dr 14999xxx (I forgot the exact number, but I remember it was 149-something). Shouldn't it Dr 1000000.00 ?

I'll give you the screenshot toninght.

@kjcpa 
Hi Kenny, thank you so much. Hope this project can be revamped and developed further.

**Comment by prashants** [comment] 2013-03-09 04:54
Hi,

I am not developing any new features but if there are any bugs or small issues I will fix them. I someone wants to develop it further I dont mind accepting patches or transferring the project to that person.

@kjcpa - I didnt get your patches.

@zxcasv - I will check that this sunday when I get free time. Meanwhile if you can send a screenshot I can push that changes in the next version of webzash.

I will try to get the period wise reports done this weekend !

"Because Dr = Cr, when a new ledger account is created, it is better to have the user to input the opening balance to both Dr and Cr sides. Or, don't allow the users to input the opening balance at all, and let them do it under Entries. The O/P Balance under Account does not have to be used."

kjcpa - One can always balance the Dr side in one ledger and Cr in other ledger as long as the total matches. It cant be done in entries since it will have issues in doing a carry forward for the next year.

"One database only. I can use the Change option to change accounting year, so it is not necessary to use one database for each year."

I thought about that before also but it didnt turn out feasible. You can use two separate browsers to see two years simultaneously. Or maybe use multiple database connections or table prefixes to sort out these issues. I am open to accepting patches for table prefixes.

Regards.

**Comment by kjcpa** [comment] 2013-03-09 16:24
I sent out the whole application folder in zip file from my yahoo.com email account.

The changes I made:

Trial Balance: add "date" column to "entry_items" table.  "entry.php" controller: add 'date' => $data_date for ledger accounts.

For "ledger_model.php", add "

"->where('entry_items.date <=', $period_end)" for the Balance Sheet ledger accounts

and

"->where('entry_items.date >=', $period_start)->where('entry_items.date <=', $period_end) " for Income Statement ledger accounts.

Add a line such as "Retained Earnings Prior to Report Period" to make the "TOTAL" Dr=Cr.

You may calculate Net Income or Loss for the Report Period.

Also, add classes for each sub-group to generate each part in the balance sheet and profit and loss statement.

**Comment by kjcpa** [comment] 2013-03-09 19:08
1) Assets=Liabilities+(Capital + Retained-Earnings - prior-to-report-period + Net_Income/Loss-for-report-period).  From the very beginning to period_end date, including the opening balance. 

2)Profit and Loss: report period only. There is nothing to do with any period not withing the period between period_start and period_end.

3)The difference should be the Retained Earnings.

**Comment by kjcpa** [comment] 2013-03-09 19:47
For the "carry forward for the next year" feature. If the database becomes very big, it is better to create a new database. "carry forward for the next year" is a very good feature.

If the database is not too big, there is no need to use the Cary Forward. The Retained Earnings will take care of the prior periods. It is how Quick Books is doing.

**Comment by zxcasv** [comment] 2013-03-10 14:30
I found the problem.
The problem is if I input "100000000" (100,000,000.00) as an opening balance when adding a ledger, it shows "14100654.08" (14,100,654.08) instead.
But if I input "10000000" (10,000,000.00), it shows the correct amount.

I think it has something related into database data type.

Here I attach the screenshot.
![Webzash I Chart Of Accounts - localhost](https://f.cloud.github.com/assets/3798461/241138/00d1acac-898f-11e2-997e-dcfda10afcfd.png)

**Comment by prashants** [comment] 2013-03-11 05:21
Thanks everyone. I will check everything tonight. Mostly will have the feature integrated by this weekend.

**Comment by prashants** [comment] 2013-03-11 05:28
@ zxcasv

I just added it a the demo page

http://webzash.org/demo/index.php/account

```
AAA Ledger A/C  Dr 100000000.00 Dr 100000000.00
```

Maybe you have some entries in the vouchers. Please check that. We support up to decimal(15,2) places in the database.

**Comment by zxcasv** [comment] 2013-03-11 14:57
@Prashants

This is weird,
I tried to set up a new account, and did nothing except add new ledger with the same value 100000000, it still comes with the same error.
I'll re-download the zip-ball, and run a fresh deployment. Hope won't face the same error.

**Comment by zxcasv** [comment] 2013-03-11 15:02
@prashants 

Btw, is it possible to combine this webzash with another opensource CI-based application?
I'm thinking of combining this with opensourcepos (http://sourceforge.net/projects/opensourcepos/).. 
How do you guys think aboaut it?

**Comment by zxcasv** [comment] 2013-03-13 14:46
Just downloaded zip-ball from 1.7, deleted all webzash databases that I've used before, did fresh install on my machine, and still get the same error when entering amount more than 10000000 (8 digits).

add another screenshoot when I tried 1.000.000.000
![abc](https://f.cloud.github.com/assets/3798461/254170/8a94dc02-8bec-11e2-8bc3-e99f84bd0ca1.PNG)

fyi I installed it in XAMPP 1.7.1...

**Comment by kjcpa** [comment] 2013-03-13 15:02
The problem may be caused by XAMPP.

**Comment by prashants** [comment] 2013-03-13 15:34
Can you check the entry in the database using phpmyadmin. What is the value that is stored there.

**Comment by prashants** [comment] 2013-03-15 04:42
I am working on the period wise reports, not yet committed the code, still lot of changes to be made. Stay tuned.

**Comment by zxcasv** [comment] 2013-05-02 12:07
Hi prashants, I'm back again.

The issue is still happening.
I can't input ledger amount more than 8 digits.
If I input the amount 9 digits or more, the C/L balance always shows the wrong amount.

And I've checked into the database, the entry (ledgers.op_balance) stored is correct.

I've tried in xampp 1.7.1, and xampp 1.8.1.
Tried in another fresh installed pc also, but still happened.

I've tried download  another zip ball (https://github.com/prashants/webzash/archive/v1.x.zip) and the problem is still there.

Is there anything I can help to fix this?

**Comment by prashants** [comment] 2013-05-02 12:21
can you email me the database dump ? pshah.mumbai AT gmail DOT com

**Comment by zxcasv** [comment] 2013-05-02 15:18
email sent. :)

**Comment by prashants** [comment] 2013-05-02 17:06
I guess some issue with PHP

In the file : system/application/helpers/custom_helper.php

Can you remove the "(int)" from the following 2 lines and let me know if it works :
212                 $param1 = (int)round($param1, 0);
213                 $param2 = (int)round($param2, 0);

It will become 
212                 $param1 = round($param1, 0);
213                 $param2 = round($param2, 0);

**Comment by zxcasv** [comment] 2013-05-02 17:12
great!
That fix the problem!

**Comment by prashants** [comment] 2013-05-02 17:14
Can you check everything including the reports and print statements whether it works ok. I will need to get to the core of the issue before I commit any changes. This is a just a temp fix. I will leave this ticket open until I fix it correctly.

**Comment by prashants** [comment] 2013-05-02 17:15
Try it with even larger value.

**Comment by zxcasv** [comment] 2013-05-03 04:11
tried with amount = 123456789012345 and any 15 digits value, showed 9999999999999.99 instead.

with 10 digits, the reports and statements is correct.
but if I put 14-15 digits. it shows 9999999999999.99.
even in the database, the entry is 9999999999999.99, not the 14-15 digits value I entered.

**Comment by prashants** [comment] 2013-05-03 05:39
Maybe some internal limitation with PHP. I will check that. Is your PHP compiled with 32 bit or 64 bit ?

**Comment by zxcasv** [comment] 2013-05-03 06:05
it's 64bit..

**Comment by ghost** [comment] 2013-05-03 06:35
max supported is 13 digits + 2 decimal.

still I will check what can be done.

**Comment by zxcasv** [comment] 2013-05-17 18:13
@octabrain : thank you for reminding. :D

@prashants, have you implement the patches (options) from @kjcpa?

**Comment by prashants** [comment] 2014-09-18 08:37
I am working on totally new version of webzash based on CakePHP which wont have this problem since it will be using the bc math library, so I will close this issue.

**Closed as completed by prashants** 2014-09-18 08:37 UTC
